file:C:/Program Files/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig	http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig	http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig	core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig	core.fscache=true
file:C:/Program Files/Git/etc/gitconfig	core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig	pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig	credential.helper=manager-core
file:C:/Program Files/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/bagde/.gitconfig	core.editor="C:\Users\bagde\AppData\Local\atom\app-1.47.0\atom.exe" --wait
file:C:/Users/bagde/.gitconfig	user.name=Vishal Narnaware
file:C:/Users/bagde/.gitconfig	user.email=vishalnarnaware@outlook.com
file:C:/Users/bagde/.gitconfig	user.signingkey=1CFD39AFE0AEC08D
file:C:/Users/bagde/.gitconfig	user.username=vijaya03n
file:C:/Users/bagde/.gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/bagde/.gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/bagde/.gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Users/bagde/.gitconfig	filter.lfs.required=true
file:C:/Users/bagde/.gitconfig	gpg.program=C:\Program Files (x86)\GnuPG\bin\gpg.exe
file:C:/Users/bagde/.gitconfig	http.postbuffer=157286400
file:C:/Users/bagde/.gitconfig	http.lowspeedlimit=0
file:C:/Users/bagde/.gitconfig	alias.add=my-add
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	core.hookspath=.husky
file:.git/config	lfs.repositoryformatversion=0
file:.git/config	remote.origin.url=https://github.com/vishalnarnaware/portfolio.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	branch.main.remote=origin
file:.git/config	branch.main.merge=refs/heads/main
